version: 2
jobs:
  build:
    working_directory: ~/workspace
    environment:
      CC_TEST_REPORTER_ID: b9e39233c3899ab2883dd8afee458241518e2ec287d8d412b441ab2587c78a8b
    docker: 
      - image: node:11.10.0
    steps:
    - checkout
    - run:
        name: Download Code Climate Test Reporter
        command: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Run  tests
        command: yarn test --detectOpenHandles --coverage -u
    - run:
        name: Push Test coverage to Codeclimate
        command: |
          ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.json coverage/lcov.info
          ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.json
workflows:
  version: 2
  build-deploy:
    jobs:
    - build